sudo: false # @link https://docs.travis-ci.com/user/workers/container-based-infrastructure/

language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer selfupdate
  - composer update --no-interaction --prefer-dist
  - composer require codeclimate/php-test-reporter:@dev --dev

script:
  - ./vendor/phpunit/phpunit/phpunit -v --coverage-clover build/logs/clover.xml

after_script:
  - CODECLIMATE_REPO_TOKEN=26c0b2626c126addd624bc01a8a3a17d443655393afa8c583e400415214a29d9 ./vendor/bin/test-reporter