language: php
php:
  - nightly
  - hhvm
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer selfupdate
  - composer update --no-interaction --prefer-dist

script:
  - ./vendor/phpunit/phpunit/phpunit -v
